version: '3.8'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SQS_ENDPOINT_URL=http://localstack:4566
      - SQS_QUEUE_URL=http://localstack:4566/000000000000/my-queue
    depends_on:
      - localstack
